

#the seven print functions each draw a different line of the owls. They take the random int generated by print_two_owls as a parameter and use that as the length of either blank space or a tree a branch in between the two owls. 
def print_crown(space:int) -> None:
    print(("  .-\"-.  ") + (space * " ") + ("  .-\"-.  "))

def print_eyes(space:int) -> None:
    print((" / 4 4 \\ ") + (space * " ") + (" / 4 4 \\ ")) 
          
def print_beak(space:int) -> None:
    print((" \\_ v _/ ") + (space * " ") + (" \\_ v _/ "))

def print_chest(space:int) -> None:
    print((" //   \\\\ ") + (space * " ") + (" //   \\\\ "))

def print_belly(space:int) -> None:
    print(("((     ))") + (space * " ") + ("((     ))"))

def print_feet(space:int) -> None:
    print(("=\"\"===\"\"=") + (space * "=") + ("=\"\"===\"\"="))

def print_tail(space:int) -> None:
    print(("   |||   ") + (space * " ") + ("   |||   "))

#this function imports the random function to generate a random number to pass to the other draw functions. It then calls the other functions in the right order to print the owls.
def print_two_owls() -> None:
    import random
    branch = random.randint(5, 20)
    print_crown(branch)
    print_eyes(branch)
    print_beak(branch)
    print_chest(branch)
    print_belly(branch)
    print_feet(branch) 
    print_tail(branch)


def main():
    print_two_owls()


main()

